---
title: "EpiCompare"
date: "<h4>Vignette updated: <i>`r format( Sys.Date(), '%b-%d-%Y')`</i></h4>"
output:
  BiocStyle::html_document
vignette: >
    %\VignetteIndexEntry{templateR} 
    %\usepackage[utf8]{inputenc}
    %\VignetteEngine{knitr::rmarkdown}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, root.dir=here::here())
knitr::opts_knit$set(echo = TRUE, root.dir=here::here())

if(!require("EpiCompare")){
    remotes::install_github("neurogenomics/EpiCompare")
}
library(dplyr)
library(EpiCompare)
data("hg19_blacklist") # example blacklist 

source(here::here("code/utils.R"))

root <- "/Volumes/bms20/projects/neurogenomics-lab/live/Data/tip_seq"
```

# Import data 

Import the called peak files produced by the [nf-core/cutanrun](https://nf-co.re/cutandrun) pipeline.

```{r}
peakfiles <- gather_files(path = file.path(root,"processed_data"),
                          type = "peaks")
picardfiles <- gather_files(path = file.path(root,"processed_data"),
                            type = "picard")
```

### Translate sample names

```{r}
batches <- data.frame(batch=list.files("/Volumes/bms20/projects/neurogenomics-lab/live/Data/tip_seq/raw_data/H3K27ac_K562_cells")) %>%
  tidyr::separate(col = "batch",into = c("V1","phase","day","month","year"),
                  remove = FALSE, sep = "_") %>%
  dplyr::mutate(date = strptime(paste(day,month,year,sep="/"),format="%d/%b/%Y", tz = "UTC"))


sample_meta <- readxl::read_excel("reports/Bulk TIP-seq samples_V2.xlsx",
                                  skip = 6) %>%
  dplyr::mutate(name = gsub(" +","",paste(`histone mark`,
                                          `antibody company`,
                                          # `antibody catalog`,
                                          # `antibody concentration`,
                                          # `cell line`,
                                          sep="_"))
                )  %>%
  data.frame() %>%  
  dplyr::left_join(batches, by="date")
sample_dict <- stats::setNames(sample_meta$name, 
                               sample_meta$batch)


#### Translate names ####
peakfiles2 <- rename_files(files = peakfiles, 
                           sample_dict = sample_dict, max_char = 50)
picardfiles2 <- rename_files(files = picardfiles, 
                             sample_dict = sample_dict, max_char = 50)
```

### Get ENCODE data

Import the full genome-wide ENCODE data since 
(`encode_H3K27ac` only includes chromosome 1).
- [H3K27ac_K562_ENCODE_ENCFF044JNJ](https://www.encodeproject.org/files/ENCFF044JNJ/) 




```{r} 
#### H3K27ac ####
encode_ac <- import.narrowPeak(con = "https://www.encodeproject.org/files/ENCFF044JNJ/@@download/ENCFF044JNJ.bed.gz")
# names(encode1)[1] <- "H3K27ac_K562_ENCODE_ENCFF044JNJ"

#### H3K27me3 ####
encode_me3 <- import.narrowPeak(con = "https://www.encodeproject.org/files/ENCFF322IFF/@@download/ENCFF322IFF.bed.gz")

ref_list <- list("encode_ac"=encode_ac,
                 "encode_me3"=encode_me3)
```


```{r}
out_list <- lapply(names(ref_list), function(nm){
  message(nm)
  save_dir <- here::here("reports",nm)
  dir.create(save_dir, showWarnings = FALSE, recursive = TRUE)
  EpiCompare(peakfiles = peakfiles2, 
             picard_files = picardfiles2,
             blacklist = hg19_blacklist,
             reference = ref_list[[nm]],
             stat_plot = TRUE,
             chrmHMM_plot = TRUE,
             chipseeker_plot = TRUE,
             enrichment_plot = TRUE,
             save_output = TRUE,
             chrmHMM_annotation = "K562",
             output_dir = save_dir)
})

```


# Session Info 

<details> 

```{r Session Info}
utils::sessionInfo()
```

</details>  

<br>
